x-app-build: &app-build
  build:
    context: .
    dockerfile: Dockerfile
  image: graph-nk:latest

# Shared runtime environment for all Python services.
x-app-env: &app-env
  env_file: .env
  environment:
    MONGO_URI:   mongodb://mongodb:27017
    REDIS_URL:   redis://redis:6379/0
    NEO4J_URI:   bolt://neo4j:7687
  restart: unless-stopped


services:
  neo4j:
    image: neo4j:2026.02.2
    container_name: graph_nk_neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: none #neo4j/${NEO4J_PASSWORD:-changeme}
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2g
      NEO4J_dbms_memory_pagecache_size: 512m
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /Volumes/Samsung SSD 990 PRO 4TB/NK-Neo4J:/data
      - /Volumes/Samsung SSD 990 PRO 4TB/NK-Neo4J:/logs

  mongodb:
    image: mongo:8.2
    container_name: graph_nk_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /Volumes/Samsung SSD 990 PRO 4TB/NK-MongoDB:/data/db

  redis:
    image: redis:latest
    container_name: graph_nk_redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy noeviction
      --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  neo4j_data:
  mongo_data:
  redis_data:
